# Generated by Django 3.1.5 on 2021-01-05 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='timing',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
