# Generated by Django 3.1.5 on 2021-01-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_auto_20210105_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='timing',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
